.PHONY: clean All

All:
	@echo "----------Building project:[ jetpac - Debug ]----------"
	@cd "jetpac" && "$(MAKE)" -f  "jetpac.mk"
clean:
	@echo "----------Cleaning project:[ jetpac - Debug ]----------"
	@cd "jetpac" && "$(MAKE)" -f  "jetpac.mk" clean
