.PHONY: clean All

All:
	@echo "----------Building project:[ box2d - Debug ]----------"
	@cd "box2d" && "$(MAKE)" -f  "box2d.mk"
clean:
	@echo "----------Cleaning project:[ box2d - Debug ]----------"
	@cd "box2d" && "$(MAKE)" -f  "box2d.mk" clean
